[package]
name = "cellular_automata"
version = "0.6.0"
edition = "2022"
author = "Ardu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.0"
egui = "0.18.1"
egui-macroquad = "0.11.0"
